### PR TITLE
Autodetect Pass path

### PR DESCRIPTION
**Pull request by alexbel**

### CODE REVIEW

**Comment by tuxor1337** [comment]
Have you tested this on Linux and Mac?

**Comment by alexbel** [comment]
Only on Linux. I don't have Mac

**Comment by tuxor1337** [comment]
I don't have Mac either, so we will probably wait forever for someone to test this on Mac...

**Comment by 5bentz** [comment]
Yes, I think so it would be easier to implement at runtime. After reading more careful #8, tuxor1337 might be willing to merge your PR instead, we'll see.

About Python,
while spending an hour or so on `subprocess`'s [docs](https://docs.python.org/3/library/subprocess.html) for a modest contribution, I found this *security consideration*, no big deal.

I really like the docs from https://docs.python.org/3/.
Especially *Library references* (for official modules such as `subprocess`) and *Language Reference* for primary variables & their methods.

For other libraries, try PyPi ;)
https://pypi.python.org/pypi

**Comment by alexbel** [comment]
Thanks! :+1:

**Pull request closed without merging**
