### PR TITLE
Added CHANGELOG

### PR DESCRIPTION
**Pull request by LucidOne**
Here is an initial attempt

### CODE REVIEW

**Comment by tuxor1337** [comment]
Thanks! Can we have a note in the "Unreleased" section that makes clear that it's currently empty? Just a line "There are currently no unreleased changes." like in https://github.com/cucumber/cucumber-rails/blob/master/CHANGELOG.md

**Comment by LucidOne** [comment]
I added it, though I wonder if it should just have 
```
## [Unreleased]
### Added
- Added CHANGELOG
```

When the next version gets released `Unreleased` is updated to `1.1.x`
Then the release is tagged without an `Unreleased` section, and a new `Unreleased` section should be added with the next pull request.

:thinking: ?

**Comment by tuxor1337** [comment]
Oh yes, that's a good start.

**Comment by LucidOne** [comment]
Done. Makes it easier if I decide to write a changelog linter to make sure `Depracated` is spelled right, lol.

**Pull request merged**
